config/routes.rb
Rails.application.routes.draw do
  #home page
  root 'pages#index'

  #devise routes for user auth
  devise_for :users
  #show user profile page
  resources :users, only: [:show]

  #for handling ajax request
  get 'search_stock', to: 'searches#stock'
  get 'search_person', to: 'searches#person'

  #handling user_stock
  resources :user_stocks, only: [:create, :destroy]

  #user portfolio
  get 'portfolio', to: 'users#portfolio'
  #user friends
  get 'friends', to: 'users#friends'
   
  #handling friendships
  resources :friendships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  # I have a pk called friend_id that references a User. 
  belongs_to :friend, class_name: 'User'

  def self.get_friendship(user_id, friend_id)
    #where is a model level query
    where(user_id: user_id, friend_id: friend_id).first
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  before_save { self.ticker = ticker.upcase }
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true


  #define class method for stock lookup
  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      # secret_token: 'Tsk_a23cbfec9acd4e98b6e86b3ce4e26c29',
      endpoint: 'https://sandbox.iexapis.com/v1'
    )

    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end

  def self.check_stock(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  #can register user, forgot password, one logged in stay signed in
  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  has_many :friendships
  has_many :friends, through: :friendships
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_stock(ticker_symbol)
    #if stock is nil, no way its tracked otherwise would be found so return false.
    return false unless stock

    #stock has been added to db alrdy, some1 tracking, check if user following stock
    stocks.where(id: stock.id).exists?
  end
  
  def under_stock_limit?
    stocks.count < 6
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def fullname
    return "#{first_name} #{last_name}" if first_name || last_name
    return "Anon"
  end


  ##### FOR SEARCH

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  #gets the records where the field_name contains th param
  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  #gets the records that correlate to search params using the helpers above.
  def self.search(param)
    param.strip! #removes leading and trailing whitespace

    #returns unique list of concatenated users.  
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq

    #if none, means user not in the database with that first/last name or email
    return nil unless to_send_back
    to_send_back
  end

  #exclude current user from a list of users
  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  #use find if you know it exists otherwise throws error
  def already_following?(user_id)
    friends.where(id: user_id).exists?
  end

  def already_tracking?(stock_id)
    stocks.where(id: stock_id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock

  def self.get_user_stock(user_id, stock_id)
    where(user_id: user_id, stock_id: stock_id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  #to add additional fields to the user pages provided by devise, ex: first and last name for user signup/edit page.
  #if we hit one of devise's controller, call this action
  before_action :configure_permitted_parameters, if: :devise_controller?



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:user])
    friendship = current_user.friendships.build(friend_id: friend.id)
    if friendship.save
      flash[:notice] = "Following #{friend.fullname}"
    else
      flash[:notice] = "There was an error following"
    end
    redirect_to friends_path
  end

  def destroy
    if params[:id]
      friendship = Friendship.get_friendship(current_user.id, params[:id])
      friendship.destroy
      flash[:notice] = "Stopped following"
      redirect_to friends_path
    end

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def stock
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock].upcase)
      if @stock
        respond_to do |format|
          #expects a js.erb now
          #since we in stocks controller, looks under stocks/
          format.js { render partial: 'stocks/data' }
        end
      else
        flash.now[:alert] = "Please enter a valid symbol to search"
        respond_to do |format|
          format.js { render partial: 'stocks/data' }
        end
        # respond_to do |format|
        #   #since this is in a shared partial folder, need to explicitly state the path
        #   format.js { render partial: 'shared/flashes'}
        # end
      end    
      
    else
      flash.now[:alert] = "Please enter a symbol!"
      respond_to do |format|
        format.js { render partial: 'stocks/data' }
      end
    end
  end


  def person
    if params[:person].present?
      @users = User.search(params[:person].downcase)
      @users = current_user.except_current_user(@users)
      if @users
        respond_to do |format|
          format.js { render partial: 'users/data' }
        end
      else
        flash.now[:alert] = "User not found. Try again"
        respond_to do |format|
          format.js { render partial: 'users/data' }
        end
      end    
      
    else
      flash.now[:alert] = "Please enter a email!"
      respond_to do |format|
        format.js { render partial: 'users/data' }
      end
    end
  end



end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_stock(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added"
    redirect_to portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.get_user_stock(current_user.id, params[:id])
    user_stock.destroy
    flash[:notice] = "You are not longer tracking #{stock.ticker}"
    redirect_to portfolio_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def friends
    @friends = current_user.friends
  end

  # both these render the portfolio table. 
  def portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  
    <%= render partial: 'shared/nav' %>
    <div class="container">
      <%= render partial: 'shared/flashes' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome To Finance Tracker!</h1>

app/views/shared/_flashes.html.erb
<% if flash.now[:notice] %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <b><%= flash.now[:notice] %></b>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% elsif flash.now[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <b><%= flash.now[:alert] %></b>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'FinanceTracker', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 flex-grow-1 align-items-center">
        <li class="nav-item">
          <% if request.path == portfolio_path %>
            <%= link_to 'Portfolio', portfolio_path, class:"nav-link active", aria: { current: "page" } %>
          <% else %>
            <%= link_to 'Portfolio', portfolio_path, class:"nav-link", aria: { current: "page" } %>
          <% end %>
        </li>

        <li class="nav-item">
          <% if request.path == friends_path %>
            <%= link_to 'Friends', friends_path, class:"nav-link active", aria: { current: "page" } %>
          <% else %>
            <%= link_to 'Friends', friends_path, class:"nav-link", aria: { current: "page" } %>
          <% end %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <%= fa_icon 'edit' %> Edit Profile
              <% end %>
            </li>
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item ms-auto me-4">
           <span><%= fa_icon 'user', class: "me-2" %><%= current_user.fullname %></span>
          </li>
          <li class="nav-item me-2">
            <%= link_to 'Logout', destroy_user_session_path, class: "nav-link btn btn-danger", tabindex:"-1", aria:"true", style: "color: white", method: :delete %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/stocks/_data.html.erb
<%= render partial: 'shared/flashes' %>

<% if @stock %>
  <div class="row" style="padding-left: 12px">
    <div class="card card-header col-9 flex-row justify-content-between align-items-center">
      <strong>Symbol: <%= @stock.ticker %></strong>
      <strong>Name: <%= @stock.name %></strong>
      <strong>Price: <%= @stock.last_price %></strong>
      
      <% if current_user.can_track_stock?(@stock.ticker) %>
        <%= button_to 'Add to portfolio', user_stocks_path(ticker: @stock.ticker), class: "btn btn-success" %>
      <% else %>
        <span class="badge rounded-pill bg-secondary">
        You are  
        <% if !current_user.under_stock_limit? %>
          tracking the max amount of stocks!
        </span>
        <% else %>
          already tracking this stock
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/stocks/_data.js.erb
<%# because we're in javascript land, we need to escape javascript to call the render method %>
document.querySelector('#results').innerHTML = '<%= j render 'stocks/data.html' %>'

app/views/users/_data.html.erb
<%= render partial: 'shared/flashes' %>

<% if @users %>
  <div class="row" style="padding-left: 12px">
    <div class="card card-header col-10">
    <table>
      <tbody>
        <% @users.each do |user| %>
            <tr>
              <td><strong>Email: <%= user.email %></strong></td>
              <td><strong>Name: <%= user.fullname %></strong></td>
              <td><%= link_to 'View Profile', user_path(user), class: "btn btn-sm btn-success" %></td>
              
              <% if !current_user.already_following?(user.id) %>
                <td><%= button_to 'Follow', friendships_path(user: user), class: "btn btn-sm btn-success" %></td>
              <% else %>
                <td><%= link_to 'Unfollow', friendship_path(user), class: "btn btn-sm btn-danger" %></td>
              <% end %>
            </tr>
          </div>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_data.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/data.html' %>'

app/views/users/_friends_cell.html.erb
<tbody>
  <tr>
    <th scope="row"><%= friend.email %></td>
    <td><%= friend.first_name %></td>
    <td><%= friend.last_name %></td>
    <td>
       <%= link_to 'View Profile', user_path(friend), class: "btn btn-sm btn-success" %>
      <%= link_to 'Unfollow', friendship_path(friend), method: :delete, class: "btn btn-sm btn-danger", data: {confirm: "Are you sure you want to untrack"} %>
    </td>
  </tr>
</tbody>

app/views/users/_friends_table.html.erb
<% if @friends %>
  <div class="row mt-3">
    <div class="col-sm-9 pe-0">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Email</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <% @friends.each do |friend| %>
          <%= render partial: 'friends_cell', locals: {friend: friend }  %>
        <% end %>
      </table>
    </div>
  </div>
<% end %>

app/views/users/_portfolio_cell.html.erb
<tbody>
  <tr>
    <th scope="row"><%= stock.ticker %></td>
    <td><%= stock.name %></td>
    <td><%= stock.last_price %></td>
    <td>
      <% if current_user.id == @user.id  %>
        <%= link_to 'Untrack', user_stock_path(stock), method: :delete, class: "btn btn-sm btn-warning", data: {confirm: "Are you sure you want to untrack"} %>
      <% else %>
        <% if current_user.already_tracking?(stock.id) %>
          <%= link_to 'Untrack', user_stock_path(stock), method: :delete, class: "btn btn-sm btn-warning", data: {confirm: "Are you sure you want to untrack"} %>
        <% else %>
          <% if current_user.under_stock_limit? %>
            <%= button_to 'Track', user_stocks_path(ticker: stock.ticker), class: "btn btn-sm btn-success" %>
          <% else %>
            <span class="badge rounded-pill bg-danger">Following max!</span>
          <% end %>
        <% end %>
      <% end %>
    </td>
  </tr>
</tbody>

app/views/users/_portfolio_table.html.erb
<div class="row mt-3">
  <div class="col-sm-9 pe-0">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <% @tracked_stocks.each do |stock| %>
        <%= render partial: 'portfolio_cell', locals: {stock: stock }  %>
      <% end %>
    </table>
  </div>
</div>

app/views/users/friends.html.erb
<div class="search-area mt-5">
  <h2>Search People</h2>
  <%= form_with(url: search_person_path, method: :get, local: false) do |f|%>
      <div class="form-group row">
        <div class="col-sm-9 pe-0">
          <%= f.text_field :person, placeholder: "Enter a name or email", autofocus: true, class: "form-control form-control-lg" %>
        </div>
        <div class="col-sm-3 ps-0">
          <%= f.button class: "btn btn-success" do %>
            <%= fa_icon 'search 2x' %>
          <% end %>
        </div>
      </div>
  <% end %>
  
  <div id="friend-results" class="mt-3 mb-3">
  </div>

  <% if @friends.count > 0 %>
    <h2>Following</h2>
    <%= render partial: 'friends_table' %>
  <% end %>
</div>

app/views/users/portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-area mt-5">
  <h3>Search Stocks</h3>
  <%= form_with(url: search_stock_path, method: :get, local: false) do |f|%>
      <div class="form-group row">
        <div class="col-sm-9 pe-0">
          <%= f.text_field :stock, placeholder: "Enter stock", autofocus: true, class: "form-control form-control-lg" %>
        </div>
        <div class="col-sm-3 ps-0">
          <%= f.button class: "btn btn-success" do %>
            <%= fa_icon 'search 2x' %>
          <% end %>
        </div>
      </div>
  <% end %>
  
  <div id="results" class="mt-3">
  </div>

  <% if @tracked_stocks.count > 0 %>
    <%= render partial: 'portfolio_table' %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.fullname %> Profile</h1>
<div>
  <table class="col-9 mt-5">
    <tbody>
      <tr>
        <td><strong>Email: <%= @user.email %></strong></td>
  
        <td>
          <% if !current_user.already_following?(@user.id) %>
            <%= button_to 'Follow', friendships_path(user: @user), class: "btn btn-sm btn-success" %>
          <% else %>
            <%= link_to 'Unfollow', friendship_path(@user), class: "btn btn-sm btn-danger" %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>

  <% if !@tracked_stocks.empty? %>
    <%= render 'users/portfolio_table' %>
  <% else %>
    <h3 class="mt-5">This user is not tracking any stocks!</h2>
  <% end %>
</div>